### ISSUE TITLE
Cannot execute test.sh

### ISSUE THREAD

**Issue by mihaigalos** [rksm/cargo-add-dynamic#1]
Hi,

Nice work!
I'm trying to run `test.sh`. I get:
```bash
$ ./test.sh
error: Found argument 'foo' which wasn't expected, or isn't valid in this context

USAGE:
    cargo rm [OPTIONS]

For more information try --help
```
Which version of [`cargo-rm`](https://crates.io/crates/cargo-rm) are you using? I've installed latest with `cargo install cargo-rm`.

Seems my version doesn't take any args (see stderr) as needed [here](https://github.com/rksm/cargo-add-dynamic/blob/3108031fdc6a0046d2e2df8787029bf84fa4fa19/clean.sh#L7).

**Comment by rksm** [comment]
probably the version from cargo-edit. I'll update the script to not use `cargo rm`.
